# -*- coding: utf-8 -*-
"""qa_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvavWwa-BzLEUWufofdROLrI6-B55unf
"""

import streamlit as st
from main_code1 import get_answer  # Import the function from qa_model.py

def main():
    # Streamlit App Title
    st.title("Question Answering System using BERT")

    # Example Context
    context = """
    The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France.
    It is named after the engineer Gustave Eiffel, whose company designed and built the tower.
    Constructed from 1887 to 1889 as the entrance arch to the 1889 World's Fair, it was initially criticized
    by some of France's leading artists and intellectuals for its design.
    """

    # Display Context
    st.subheader("Context:")
    st.write(context)

    # User Input: Question
    question = st.text_input("Enter your question:")

    # Get Answer Button
    if st.button("Get Answer"):
        if question:
            answer = get_answer(context, question)
            st.success(f"**Answer:** {answer}")
        else:
            st.warning("⚠️ Please enter a question.")

if __name__ == "__main__":
    main()